services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_DB: ccdr-explorer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Init scripts are only executed on first database initialization
      - ./artifacts/initdb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

volumes:
  postgres-data: 